### ISSUE TITLE
[0.5.1] Adding a second NIC crashes tf apply

### ISSUE THREAD

**Issue by danimo** [OpenNebula/terraform-provider-opennebula#313]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### Affected Resource(s)

- `opennebula_virtual_machine`

### Panic Output
```
│ Error: Plugin did not respond
│ 
│   with opennebula_virtual_machine.reproducer,
│   on node.tf line 1, in resource "opennebula_virtual_machine" "reproducer":
│    1: resource "opennebula_virtual_machine" "reproducer" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call.
│ The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-opennebula plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 11 [running]:
github.com/OpenNebula/terraform-provider-opennebula/opennebula.updateNIC({0xdf06f0, 0xc000088420}, 0xc0003f46c0?, {0xb82940?, 0xc0003464a0?})
        /home/danimo/dev/infra.run/terraform-provider-opennebula/opennebula/resource_opennebula_virtual_machine.go:1863 +0xe1b
github.com/OpenNebula/terraform-provider-opennebula/opennebula.customVirtualMachineUpdate({0xdf06f0, 0xc000088420}, 0xc0000f4300, {0xb82940, 0xc0003464a0})
        /home/danimo/dev/infra.run/terraform-provider-opennebula/opennebula/resource_opennebula_virtual_machine.go:1064 +0x9a
github.com/OpenNebula/terraform-provider-opennebula/opennebula.resourceOpennebulaVirtualMachineUpdateCustom({0xdf06f0, 0xc000088420}, 0xc0000f4300, {0xb82940, 0xc0003464a0}, 0xd0cce0)
        /home/danimo/dev/infra.run/terraform-provider-opennebula/opennebula/resource_opennebula_virtual_machine.go:1282 +0x2029
github.com/OpenNebula/terraform-provider-opennebula/opennebula.resourceOpennebulaVirtualMachineUpdate({0xdf06f0, 0xc000088420}, 0xbdb620?, {0xb82940, 0xc0003464a0})
        /home/danimo/dev/infra.run/terraform-provider-opennebula/opennebula/resource_opennebula_virtual_machine.go:1051 +0x39
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0004bf6c0, {0xdf0680, 0xc000330d80}, 0x24?, {0xb82940, 0xc0003464a0})
        /home/danimo/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:375 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004bf6c0, {0xdf0680, 0xc000330d80}, 0xc00035e750, 0xc00013d500, {0xb82940, 0xc0003464a0})
        /home/danimo/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:475 +0x53a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00011a7f8, {0xdf0680, 0xc000330d80}, 0xc00033b5e0)
        /home/danimo/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00013cd00, {0xdf0728?, 0xc00051b9b0?}, 0xc000466230)
        /home/danimo/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc89c80?, 0xc00013cd00}, {0xdf0728, 0xc00051b9b0}, 0xc00030a900, 0x0)
        /home/danimo/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00042f340, {0xdf3480, 0xc0002fc000}, 0xc0002a4500, 0xc00051a030, 0x12b3300, 0x0)
        /home/danimo/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc00042f340, {0xdf3480, 0xc0002fc000}, 0xc0002a4500, 0x0)
        /home/danimo/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/danimo/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/danimo/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x28a

Error: The terraform-provider-opennebula plugin crashed!
```

### Expected Behavior

Second NIC gets added

### Actual Behavior

Crash (see above)

### Steps to Reproduce

1. Create `opennebula_virtual_machine` resource with a single NIC ("reproducer" in crash above)
2. `terraform apply`
3. Add another NIC
4. `terraform apply`
5. Observe crash

**Comment by frousselet** [comment]
Hello @danimo,

Thanks for pointing this out.

Could you include the `TF_LOG=TRACE` output please? We are not able to reproduce this issue on our side.

Many thanks.

**Comment by danimo** [comment]
@frousselet with a newly created VM we cannot reproduce it either. The state that caused the error originally was left from a 0.5.0 setup (or even older). Someone from my team will get back to you once we get to reproduce this.
